repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.14
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-illegal-windows-names
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: check-yaml
      - id: debug-statements
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: "v3.8.1"
    hooks:
      - id: prettier
        types_or: [html]
  - repo: local
    hooks:
      - id: local-biome-check
        name: biome check
        entry: npx @biomejs/biome check --write --files-ignore-unknown=true --no-errors-on-unmatched
        language: system
        types: [text]
        files: "\\.(jsx?|tsx?|c(js|ts)|m(js|ts)|d\\.(ts|cts|mts)|jsonc?)$"
  - repo: https://github.com/jorisroovers/gitlint
    rev: "v0.19.1" # pick a tag / sha to use
    hooks:
      - id: gitlint
