on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      test:
        type: boolean
        required: false

env:
  python-version: 3.12.11
  node-version: 25.8.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}
          enable-cache: true
          working-directory: backend

      - name: Install the backend project
        run: uv sync --locked
        working-directory: backend

      - name: Export requirements.txt
        run: uv export --format requirements.txt > requirements-new.txt
        working-directory: backend

      - name: Upload requirements.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: requirements.txt
          path: backend/requirements-new.txt

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.node-version }}
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: frontend

      - name: Run frontend tests
        if: inputs.test == true || vars.test == true
        run: pnpm ng test
        working-directory: frontend

      # - name: Run backend tests
      #   run: uvx pytest tests
      #   working-directory: backend

      - name: Build angular app
        run: pnpm ng build
        working-directory: frontend

      - name: Upload angular artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-artifact
          path: frontend/dist/frontend/browser

  deploy:
    # permissions:
    #   contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v6

      - name: Download requirements.txt artifact
        uses: actions/download-artifact@v4
        with:
          name: requirements.txt
          path: backend

      - name: Generate .env
        run: |
          echo "ARCHIE_ALLOWED_HOSTS=api.${{ vars.WEBSITE_HOST }},www.api.${{ vars.WEBSITE_HOST }}" >> .env
          echo "ARCHIE_STATIC_URL=https://static.api.${{ vars.WEBSITE_HOST }}/" >> .env
          echo "ARCHIE_STATIC_ROOT=/home/${{ vars.USER }}/domains/static.api.${{ vars.WEBSITE_HOST }}/public_html" >> .env
          echo "ARCHIE_SECRET_KEY=secret" >> .env
          echo "ARCHIE_USE_HTTPS=true" >> .env
        working-directory: backend

      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: angular-artifact
          path: ./angular

      - name: Show file structure
        run: |
          tree -a .
          file backend/requirements-new.txt

      - name: Rsync backend
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -azr --delete
          path: backend/
          remote_path: ${{ vars.BACKEND_PROJECT_FOLDER }} # ex: /var/www/html/
          remote_host: ${{ secrets.SSH_HOST }} # ex: example.com
          remote_port: ${{ secrets.SSH_PORT }} # ex: 22
          remote_user: ${{ secrets.SSH_USER }} # ex: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}
          remote_key_pass: ${{ secrets.SSH_PASSPHRASE }}

      - name: Setup backend
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            cd ~/${{ vars.BACKEND_PROJECT_FOLDER }}
            tree -a ..
            file requirements-new.txt
            source ~/${{ vars.VENV_ACTIVATE_PATH }}
            cp -f passenger_wsgi.py ..
            pip install -r requirements-new.txt
            mv -f requirements-new.txt requirements.txt
            python manage.py collectstatic --noinput
            python manage.py migrate
            touch ../tmp/restart.txt

      - name: Rsync frontend
        uses: burnett01/rsync-deployments@v8
        with:
          switches: -azr --delete
          path: angular/
          remote_path: ${{ vars.FRONTEND_PROJECT_FOLDER }} # ex: /var/www/html/
          remote_host: ${{ secrets.SSH_HOST }} # ex: example.com
          remote_port: ${{ secrets.SSH_PORT }} # ex: 22
          remote_user: ${{ secrets.SSH_USER }} # ex: ubuntu
          remote_key: ${{ secrets.SSH_KEY }}
          remote_key_pass: ${{ secrets.SSH_PASSPHRASE }}
